### PR TITLE
Fix length in ratatui render spark_area

### LINKED ISSUE #1: Crash when resizing terminal (in Vscode)
Crash when resizing terminal (in Vscode)

```
thread '<unnamed>' panicked at /Users/mamalakis/.cargo/registry/src/in
•crates.io-6f17d22bba15001f/ratatui-0.26.3/src/widgets/sparkline.rs:209
Trying to access position outside the buffer: x=74, y=9, area=Rect { x
• y: 0, width: 74, height: 18 } note: run with 'RUST_BACKTRACE=1' enviro
nt variable to display a backtrace
```

Assignees: @bugos
Labels: 
Milestone: 
Projects:

### PR DESCRIPTION
**Pull request by bugos**
Fixes #1

### CODE REVIEW

File: src/decoder.rs [hunk 1]
```diff
@@ -47,8 +47,8 @@ impl Widget for &Decoder {
         Widget::render(list, list_area, buf);
 
         let lock: std::sync::RwLockReadGuard<State> = self.state.read().unwrap();
-        let spark_area = Rect::new(0, 8, lock.buf.buf.len() as u16, 3).offset(offset);
-        let data: Vec<_> = lock.buf.iter().map(|dp| if dp {1u64} else { 0u64}).collect();
+        let spark_area = Rect::new(0, 8, buf.area().width as u16, 3).offset(offset);
+        let data: Vec<_> = lock.buf.iter().map(|dp: bool| if dp {1u64} else { 0u64}).collect();
```
Comment (Mandragorian) [inline src/decoder.rs]: Please remove the type annotation here. It is not needed.
